services:
  app:
    build: .
    env_file:
      - .env
    restart: always
  db:
    image: mysql:8.0.30
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: yakudobot_db
    restart: always
volumes:
  db_data: